# .github/workflows/data_pipeline.yml
name: Data Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes

jobs:
  run-data-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure AWS credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region us-east-1 # or your preferred region

    - name: Run data pipeline
      run: |
        python data_pipeline.py
